### ISSUE TITLE
Split of small negative values doesn't work properly

### ISSUE THREAD

**Issue by arzonus** [Rhymond/go-money#106] opened 2022-04-04 16:40 UTC
I found that a small negative amount will be split wrongly.

**Example**

```go
package main

import (
	"fmt"

	"github.com/Rhymond/go-money"
)

func main() {
	var val = money.New(-2, "EUR")
	parts, err := val.Split(3)
	if err != nil {
		fmt.Println(err)
	}

	for _, part := range parts {
		fmt.Println(part.Display())
	}
}
```

**Expected output**
```
-€0.01
-€0.01
-€0.00
```

**Actual output**
```
€0.01
€0.01
€0.00
```

It seems that if a money value is less than the number of split parts it returns a wrong sign because 0.04/3 returns 0.02,0.01,0.01.

**Comment by Rhymond** [comment] 2022-04-08 16:25
Thanks, Great find! The issue is fixed and released in v1.0.6 release

**Closed by Rhymond** 2022-04-08 16:25 UTC
